### ISSUE TITLE
What's the ETA for a TypeScript version?

### ISSUE THREAD

**Issue by IvanFarkas** [mourner/robust-predicates#5]
# What's the ETA for a TypeScript version?

Great library!

Since it has the type file to be TypeScript compatible I can use this JavaScript implementation in my TypeScript code,
Unfortunately, in my tests, using jest, I am getting an error that I was not able to overcome.
Also, I'd like to use macros in my code as well and learn from the TypeScript implementation.

Error:
```shell
$ yarn test
yarn run v1.22.17
$ jest
 FAIL  test/unit/MathUtils.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/user/project/node_modules/robust-predicates/index.js:2
    export {orient2d, orient2dfast} from './esm/orient2d.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | /* eslint-disable no-constant-condition */
      2 |
    > 3 | import {orient2d} from 'robust-predicates';
        | ^
      4 |
      5 | const EPSILON = Math.pow(2, -52);
      6 | const EDGE_STACK = new Uint32Array(512);

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/components/Delaunator.ts:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        16.894 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by IvanFarkas** [comment]
# Workaround till fixed

[**[Bug]: Unexpected token 'export' when Jest test imports d3 (7.1.1) #12036**](https://github.com/facebook/jest/issues/12036)

**jest.config.ts** Jest config file

```typescript
// jest.config.ts

import type {InitialOptionsTsJest} from 'ts-jest';
// import {defaults as tsjPreset} from 'ts-jest/presets';
// import {defaultsESM as tsjPreset} from 'ts-jest/presets';
// import {jsWithTs as tsjPreset} from 'ts-jest/presets';
// import {jsWithTsESM as tsjPreset} from 'ts-jest/presets';
import {jsWithBabel as tsjPreset} from 'ts-jest/presets'; // OK with robust-predicates
// import {jsWithBabelESM as tsjPreset} from 'ts-jest/presets'; // OK with robust-predicates

const config: InitialOptionsTsJest = {
  verbose: true,
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: [
    '**/?(*.)+(spec|test).[t]s?(x)', // The glob patterns Jest uses to detect test files
  ],
  transform: {
    ...tsjPreset.transform,
  },
  transformIgnorePatterns: ['/node_modules/(?!delaunator|robust-predicates)'],
};

export default config;
```

**Comment by mourner** [comment]
This library already provides TypeScript types. For questions on how to use ES module libraries in your apps, please consult StackOverflow or Google.
